import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("datasets\Adults.csv")

print("choose your choice :")
print("1 : age")
print("2 : workclass")
print("3 : education")
print("4 : marital-status")
print("5 : occupation")
print("6 : race")
print("7 : sex")
print("8 : hoursPerWeek")
print("9 : nativeCountry")
print("10 : income")
x = int(input("Enter your choice : "))
if x ==1:
    grouped = data.groupby('age').size()
    print(grouped)
    plt.figure(figsize=(8,5))
    plt.hist(data['age'],kde=True,bins=30)
    plt.title("histplot")
    plt.xlabel('age')
    plt.tight_layout()
    plt.show()
if x ==2:
    grouped = data.groupby('workclass').size()
    print(grouped)
    plt.figure(figsize=(8,5))
    sns.histplot(data['workclass'],kde=True,bins=30)
    plt.title("histplot")
    plt.xlabel('workclass')
    plt.tight_layout()
    plt.show()
    
if x == 3:
    grouped = data.groupby('education').size()
    print(grouped)
    plt.figure(figsize=(8,5))
    sns.histplot(data['education'],kde=True,bins=30)
    plt.title("histplot")
    plt.xlabel('education')
    plt.tight_layout()
    plt.show()
if x ==4:
    grouped = data.groupby('marital-status').size()
    print(grouped)
    plt.figure(figsize=(8,5))
    sns.histplot(data['marital-status'],kde=True,bins=30)
    plt.title("histplot")
    plt.xlabel('marital-status')
    plt.tight_layout()
    plt.show()
if x ==5:
    grouped = data.groupby('occupation').size()
    print(grouped)
    plt.figure(figsize=(8,5))
    sns.histplot(data['occupation'],kde=True,bins=30)
    plt.title("histplot")
    plt.xlabel('occupation')
    plt.tight_layout()
    plt.show()
if x ==6:
    grouped = data.groupby('race').size()
    print(grouped)
    plt.figure(figsize=(8,5))
    sns.histplot(data['race'],kde=True,bins=30)
    plt.title("histplot")
    plt.xlabel('race')
    plt.tight_layout()
    plt.show()
if x ==7:
    grouped = data.groupby('sex').size()
    print(grouped)
    plt.figure(figsize=(8,5))
    sns.histplot(data['sex'],kde=True,bins=30)
    plt.title("histplot")
    plt.xlabel('sex')
    plt.tight_layout()
    plt.show()
if x ==8:
    grouped = data.groupby('hoursPerWeek').size()
    print(grouped)
    plt.figure(figsize=(8,5))
    sns.histplot(data['hoursPerWeek'],kde=True,bins=30)
    plt.title("histplot")
    plt.xlabel('hoursPerWeek')
    plt.tight_layout()
    plt.show()
if x ==9:
    grouped = data.groupby('nativeCountry').size()
    print(grouped)
    plt.figure(figsize=(8,5))
    sns.histplot(data['nativeCountry'],kde=True,bins=30)
    plt.title("histplot")
    plt.xlabel('nativeCountry')
    plt.tight_layout()
    plt.show()
if x ==10:
    grouped = data.groupby('income').size()
    print(grouped)
    plt.figure(figsize=(8,5))
    sns.histplot(data['income'],kde=True,bins=30)
    plt.title("histplot")
    plt.xlabel('income')
    plt.tight_layout()
    plt.show()
