import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df= pd.read_csv('airports.csv')
df.to_csv('airports.csv', index=False)
print("\nRead CSV:")
print(df)
plt.figure(figsize=(8, 5))
plt.bar(df['Grade'], df['GPA'], color=['blue', 'green', 'red', 'purple', 'orange', 'pink', 'violet', 'yellow', 'brown', 'grey'], label='GPA')
plt.ylabel('GPA')
plt.title('Bar Chart of GPA by Grade')
plt.show()
x_scatter = np.random.rand(50)
y_scatter = np.random.rand(50)
plt.figure(figsize=(8, 5))
plt.scatter(x_scatter, y_scatter, color='r', marker='o', label='Data Points')
plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.title('Scatter Plot')
plt.legend()
plt.grid()
plt.show()
x = np.linspace(0, 10, 100)
y = np.sin(x)
plt.figure(figsize=(8, 5))
plt.plot(x, y, label='Sine Wave', color='b', linestyle='-', linewidth=2)
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.title('Line Plot')
plt.legend()
plt.grid()
plt.show()

